# Generated by Django 5.0.9 on 2025-02-14 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría', max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción de la categoría', verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del producto o servicio', max_length=200, verbose_name='nombre')),
                ('type', models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio')], help_text='Tipo de ítem (producto o servicio)', max_length=10, verbose_name='tipo')),
                ('description', models.TextField(help_text='Descripción detallada', verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del producto o servicio', max_digits=10, verbose_name='precio')),
                ('currency', models.CharField(default='MXN', help_text='Moneda del precio', max_length=3, verbose_name='moneda')),
                ('unit', models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('lb', 'Libra'), ('oz', 'Onza'), ('lt', 'Litro'), ('ml', 'Mililitro'), ('m', 'Metro'), ('cm', 'Centímetro'), ('mm', 'Milímetro'), ('ft', 'Pie'), ('in', 'Pulgada'), ('pkg', 'Paquete'), ('box', 'Caja'), ('roll', 'Rollo'), ('dozen', 'Docena'), ('set', 'Juego'), ('pair', 'Par')], default='unit', help_text='Unidad de medida del producto', max_length=10, verbose_name='unidad de medida')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el producto o servicio', null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('is_available', models.BooleanField(default=True, help_text='Indica si el producto o servicio está disponible', verbose_name='disponible')),
                ('image', models.ImageField(blank=True, help_text='Imagen del producto o servicio', null=True, upload_to='products/', verbose_name='imagen')),
                ('category', models.ForeignKey(help_text='Categoría del producto o servicio', on_delete=django.db.models.deletion.PROTECT, to='supplier_items.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['name'],
            },
        ),
    ]
