"""
Django settings for suppliersPortal project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as message_constants


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/html/DjangoProjetc/staticfiles/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5!6=$fu=n@v%jr=9g*2v#oa)op@e7d5e2l6av%0j-onu1^m#zv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


if not DEBUG:
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

X_FRAME_OPTIONS = 'SAMEORIGIN'

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'common',
    'apps.accounts',
    'apps.supplier',
    'apps.notifications',
    'apps.supplier_items',
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'suppliersPortal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # Aquí agregas la ruta a tu directorio 'templates'
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Agrega el context_processor que creaste
                'suppliersPortal.context_processors.companies_processor',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

WSGI_APPLICATION = 'suppliersPortal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'SuppliersPortal',
        'USER': 'cguser',
        'PASSWORD': 'sahei1712',
        'HOST': '192.168.0.6',
        'PORT': '1433',  # Por defecto SQL Server usa el puerto 1433
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    '1G_TGS_AHUMADA': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TGS_AHUMADA',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TGS_CASTANO': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TGS_CASTANO',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TGS_CLARA': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TGS_CLARA',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TGS_GASOMEX': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TGS_GASOMEX',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TGS_INMO': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TGS_INMO',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TGS_JARUDO': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TGS_JARUDO',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TGS_PETROTAL': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TGS_PETROTAL',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TGS_PICACHOS': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TGS_PICACHOS',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TGS_SERVICIOSYC': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TGS_SERVICIOSYC',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TGS_VENTANAS': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TGS_VENTANAS',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TGS_ZAID': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TGS_ZAID',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TOTALGAS': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TOTALGAS',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TOTALGAS_EC': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TOTALGAS_EC',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TOTALGAS_MCP': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TOTALGAS_MCP',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TOTALGAS_TSA': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TOTALGAS_TSA',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    },
    '1G_TGS_FORMULAGAS': {  # Base de datos de OneGoal
        'ENGINE': 'mssql',  # Cambia según el motor que uses
        'NAME': '1G_TGS_FORMULAGAS',
        'USER': 'sa',
        'PASSWORD': 'mEiLsS121806',
        'HOST': '192.168.0.5',
        'PORT': '1433',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Denver'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]



# Configuración de la sesión 1. Configurar el tiempo de expiración de la sesión en Django, 2. Configurar la expiración de la sesión al cerrar el navegador
SESSION_COOKIE_AGE = 1200
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Ruta para el directorio de medios (donde se guardan las imágenes y archivos cargados)
MEDIA_URL = '/media/'  # URL para acceder a los archivos cargados
# Ruta física de la carpeta en el sistema de archivos
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}

# Configuración básica de correo electrónico
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Usa el servidor de correo de tu elección
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'totalgasdesarrollo@gmail.com'
# Mejor utilizar un archivo .env para seguridad
EMAIL_HOST_PASSWORD = 'yckblsffteicqdho'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

SITE_URL = 'http://192.168.0.109'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"  # o 'tailwind' si es el caso
CRISPY_TEMPLATE_PACK = "bootstrap5"