# Generated by Django 5.0.9 on 2025-02-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierquoterequestitem',
            name='requisition_id',
            field=models.IntegerField(blank=True, default=0, help_text='Identificador de la requisición asociada a este ítem', null=True, verbose_name='ID de Requisición'),
        ),
        migrations.AlterField(
            model_name='supplierquoterequestitem',
            name='requisition_line',
            field=models.IntegerField(blank=True, default=0, help_text='Número de línea de la requisición asociada a este ítem', null=True, verbose_name='Línea de Requisición'),
        ),
    ]
