# Generated by Django 5.0.9 on 2025-03-06 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplierquoterequestitem_requisition_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.AutoField(help_text='Identificador único para cada cotización del proveedor', primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, help_text='Número o referencia de la cotización asignado por el proveedor', max_length=100, null=True, verbose_name='Número de Cotización')),
                ('validity_date', models.DateField(blank=True, help_text='Fecha hasta la cual es válida la cotización', null=True, verbose_name='Fecha de Validez')),
                ('delivery_time', models.CharField(blank=True, help_text='Tiempo estimado de entrega ofrecido por el proveedor', max_length=100, null=True, verbose_name='Tiempo de Entrega')),
                ('payment_terms', models.CharField(blank=True, help_text='Condiciones de pago ofrecidas por el proveedor', max_length=200, null=True, verbose_name='Condiciones de Pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal de la cotización sin impuestos', max_digits=12, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Monto total de impuestos aplicados a la cotización', max_digits=12, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Monto total de la cotización incluyendo impuestos', max_digits=12, verbose_name='Total')),
                ('currency', models.CharField(choices=[('MXN', 'Pesos'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='MXN', help_text='Moneda en la que se cotiza. Puede ser MXN (Pesos), USD (Dólares) o EUR (Euros)', max_length=3, verbose_name='Moneda')),
                ('quote_file_1', models.FileField(blank=True, help_text='Primer archivo adjunto de la cotización (PDF o DOCX)', null=True, upload_to='supplier_quotes/', verbose_name='Archivo de Cotización 1')),
                ('quote_file_2', models.FileField(blank=True, help_text='Segundo archivo adjunto de la cotización (opcional, PDF o DOCX)', null=True, upload_to='supplier_quotes/', verbose_name='Archivo de Cotización 2')),
                ('notes', models.TextField(blank=True, help_text='Notas o comentarios adicionales sobre la cotización', null=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida')], default='ENVIADA', help_text="Estado actual de la cotización. Por defecto es 'ENVIADA'", max_length=50, verbose_name='Estatus')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se recibió la cotización. Se establece automáticamente', verbose_name='Fecha de Recepción')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización de la cotización. Se actualiza automáticamente', verbose_name='Fecha de Actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la cotización. Se establece automáticamente', verbose_name='Fecha de Creación')),
                ('quote_request', models.ForeignKey(help_text='Solicitud de cotización a la que responde esta cotización. Se eliminará si se elimina la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='supplier.supplierquoterequest', verbose_name='Solicitud de Cotización')),
                ('supplier', models.ForeignKey(db_column='supplier_id', help_text='Proveedor que envía la cotización. Se eliminarán todas las cotizaciones si se elimina el proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='supplier.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Cotización de Proveedor',
                'verbose_name_plural': 'Cotizaciones de Proveedores',
                'db_table': 'supplier_quote',
            },
        ),
    ]
