# Generated by Django 5.0.9 on 2025-03-08 00:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplierquote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address_proof',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='bank_statement',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='confidentiality_agreement',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='fiscal_situation',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='imss_opinion',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='incorporation_act',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='induction_course',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='infonavit_opinion',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='legal_power',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='repse',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='sat_positive_opinion',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_registration_request',
        ),
        migrations.AddField(
            model_name='supplier',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
