# Generated by Django 5.0.9 on 2025-03-10 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_remove_supplier_address_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_required', models.BooleanField(default=False, verbose_name='Es obligatorio')),
                ('upload_path', models.CharField(help_text='Ruta relativa donde se almacenarán los archivos', max_length=255, verbose_name='Ruta de subida')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='supplier_documents/', verbose_name='Archivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_documents', to='supplier.documenttype', verbose_name='Tipo de documento')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='supplier.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Documento de proveedor',
                'verbose_name_plural': 'Documentos de proveedores',
                'ordering': ['-uploaded_at'],
                'unique_together': {('supplier', 'document_type')},
            },
        ),
    ]
