# Generated by Django 5.0.9 on 2025-06-09 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_load_document_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Nombre descriptivo de la solicitud de cotización', max_length=100, verbose_name='Folio')),
                ('description', models.TextField(blank=True, help_text='Información adicional sobre la solicitud', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Momento en que se creó la RFQ', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó la RFQ', verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(help_text='Usuario que generó la solicitud de cotización', on_delete=django.db.models.deletion.CASCADE, related_name='rfqs_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
            ],
            options={
                'verbose_name': 'Solicitud de cotización',
                'verbose_name_plural': 'Solicitudes de cotización',
            },
        ),
    ]
