# Generated by Django 5.0.9 on 2025-06-09 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_rfq'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquoterequest',
            name='rfq',
            field=models.ForeignKey(blank=True, help_text='Solicitud de cotización (cabecera) a la que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='supplier.rfq', verbose_name='RFQ asociada'),
        ),
    ]
