# Generated by Django 5.0.9 on 2025-02-11 18:58

import django.db.models.deletion
import apps.notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(
                    help_text='Título corto y descriptivo de la notificación', max_length=200, verbose_name='Título')),
                ('description', models.TextField(
                    blank=True, help_text='Descripción detallada de la notificación (opcional)', null=True, verbose_name='Descripción')),
                ('link', models.URLField(
                    blank=True, help_text='URL relacionada con la notificación (opcional)', null=True, verbose_name='Enlace')),
                ('notification_type', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('success', 'Éxito'), (
                    'error', 'Error')], default='info', help_text='Categoría de la notificación: información, advertencia, éxito o error', max_length=10, verbose_name='Tipo de Notificación')),
                ('priority', models.IntegerField(
                    default=0, help_text='Nivel de prioridad de la notificación. Mayor número indica mayor prioridad', verbose_name='Prioridad')),
                ('expires_at', models.DateTimeField(
                    blank=True, help_text='Fecha y hora en que la notificación dejará de ser válida (opcional)', null=True, verbose_name='Fecha de Expiración')),
                ('action_text', models.CharField(blank=True, help_text='Texto que se mostrará en el botón de acción de la notificación (opcional)',
                 max_length=50, null=True, verbose_name='Texto del botón de acción')),
                ('is_read', models.BooleanField(default=False,
                 help_text='Indica si la notificación ha sido leída por el usuario', verbose_name='Leído')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que la notificación fue vista por primera vez',
                 null=True, verbose_name='Fecha de Visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                 help_text='Fecha y hora en que se creó la notificación', verbose_name='Fecha de Creación')),
                ('created_by', models.ForeignKey(default=apps.notifications.models.get_default_user, help_text='Usuario que crea la notificación (por defecto el primer superadministrador)',
                 on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('recipient', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE,
                 related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='notificatio_created_3f253c_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx')],
            },
        ),
    ]
